install.packages("arules")
install.packages("arulesViz")
library('arules')
library('arulesViz')
tr <- read.transactions("E:/UNIVERSITAS BRAWIJAYA/SEMESTER 6/DATA MINING/DataMiningP4Groceries.csv", format = 'basket', sep = ',')
summary(tr)
data1 <- apply(tr@data,2,function(r)paste(tr@itemInfo[r,"labels"],collapse =","))
head(data1)
itemsets1 <- apriori(tr,parameter=list(minlen=1,maxlen=1,support=0.02,target="frequent itemsets"))      
inspect(head(sort(itemsets1, by="support"),10))
itemsets2 <- apriori(tr,parameter=list(minlen=2,maxlen=2,support=0.02,target="frequent itemsets"))
itemsets <- apriori(tr,parameter=list(minlen=1,support=0.02,target="frequent itemsets"))
rules <- apriori(tr,parameter=list(support=0.001,confidence=0.6,target="rules"))
plot(rules)
plot(rules@quality[,1:3])
ConfidentRules <- rules[quality(rules)$confidence>0.9]
ConfidentRules
inspect(head(sort(ConfidentRules, by="confidence"),10))
inspect(head(sort(rules, by="lift"),10))
HighliftRules <- head(sort(rules, by="lift"),5)
plot(HighliftRules, method = "graph", control=list(type="items"))
